#!/bin/bash -
#
# rcheck - recussive check
#
# @(#) $Revision: 1.12 $
# @(#) $Id: testcfg,v 1.12 2003/09/17 05:50:37 chongo Exp $
# @(#) $Source: /usr/local/src/etc/testcfg/RCS/testcfg,v $
#
# Copyright (c) 2002 by Landon Curt Noll.  All Rights Reserved.
#
# Permission to use, copy, modify, and distribute this software and
# its documentation for any purpose and without fee is hereby granted,
# provided that the above copyright, this permission notice and text
# this comment, and the disclaimer below appear in all of the following:
#
#       supporting documentation
#       source copies
#       source works derived from this source
#       binaries derived from this source or from derived source
#
# LANDON CURT NOLL DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO
# EVENT SHALL LANDON CURT NOLL BE LIABLE FOR ANY SPECIAL, INDIRECT OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
# USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.
#
# chongo (Landon Curt Noll, http://www.isthe.com/chongo/index.html) /\oo/\
#
# Share and enjoy! :-)

# setup
#
if [[ ! -x /usr/local/bin/check ]]; then
    echo "$0: Fatal: /usr/local/bin/check is not executable/found" 1>&2
    exit 1
fi
if [[ $# -lt 1 ]]; then
    ARG_SET="$PWD"
else
    ARG_SET="$@"
fi

# look for RCS checked out config files
#
/usr/bin/find $ARG_SET -name RCS -type d -print 2>/dev/null |
  /bin/egrep -v '/\.OLD/|/UNUSED/' |
  while read rcsdir; do
    if [[ ! -x "$rcsdir" || ! -r "$rcsdir" ]]; then
	echo "# Warning: cannot read/search $rcsdir" 1>&2
	continue
    fi
    dir=`/usr/bin/dirname "$rcsdir"`
    /usr/local/bin/check "$rcsdir" | /bin/sed -e "s:^:$dir/:"
  done

# All done!!  -- Jessica Noll, Age 2
#
exit 0
